### ISSUE TITLE
animatie makkelijker schrijven

### ISSUE THREAD

**Issue by SamaraFellaDina** [Naddybsx/the-startup-responsive-interactive-website#13]
https://github.com/Naddybsx/the-startup-responsive-interactive-website/blob/77bd8690673d24b14ed6f4034b415063a36dcf55/styles/style.css#L161-L166

je kan hem makkelijker schrijven

```css
/* Animation slider */
@keyframes slide {
    0% {
      transform: translateY(0); 
}
    50% { 
      transform: translateY(-40px);
 }
    100% {
       transform: translateY(-80px); 
}}

```
